# Generated by Django 2.1.3 on 2018-11-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(upload_to='img/items/%Y/%m/%d'),
        ),
    ]
